Asfour\ActionBundle\Entity\Achivement:
  type: entity
  table: achivement
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discr
    type: string
    length: 31
  discriminatorMap:
    badge: Badge
    title: Title
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    conditions:
      type: text
    description:
      type: text
    is_active:
      type: boolean
      default: false
  oneToMany:
    aquireds:
      targetEntity: Aquired
      mappedBy: achivement
      cascade: ["persist", "merge"]
#    image:
#      type: string
#      length: 63
#      nullable: true
#    thumbnail:
#      type: string
#      length: 63
#      nullable: true
#    score:
#      type: integer
#      nullable: true
#Asfour\ActionBundle\Entity\Badge:
#  type: entity
#  attributeOverride:
#    id:
#      column: badge_id
#    image:
#      type: string
#      length: 63
#      nullable: false
#    thumbnail:
#      type: string
#      length: 63
#      nullable: false
#Asfour\ActionBundle\Entity\Title:
#  type: entity
#  attributeOverride:
#    id:
#      column: title_id
#    score:
#      type: integer
#      nullable: false