Asfour\ActionBundle\Entity\Image:
  type: entity
  table: image
  gedmo:
    uploadable:
      allowOverwrite: true
      appendNumber: true
      path: '/web/bundle/asfouraction/uplaods/images/'
      pathMethod: getPath
      callback: callbackMethod
      filenameGenerator: SHA1
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    path:
      type: string
      gedmo:
        - uploadableFilePath
    name:
      type: string
      gedmo:
        - uploadableFileName
    mimeType:
      type: string
      gedmo:
        - uploadableFileMimeType
    size:
      type: decimal
      gedmo:
        - uploadableFileSize
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    action:
      targetEntity: Action
      inversedBy: images
      joinColumn:
        name: action_id
        referencedColumnName: id