Asfour\ActionBundle\Entity\Team:
  type: entity
  table: team
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 63
    image:
      type: string
      length: 63
      nullable: true
  oneToMany:
    participants:
      targetEntity: Participant
      mappedBy: team
      cascade: ["persist", "merge"]